Home:               Home
Code:               Code
DownloadBinary:     Download this binary file by clicking on its name.
JustNow:            just now
MinutesAgo n@Int:   #{number n} #{plural n "minute" "minutes"} ago
HoursAgo n@Int:      #{number n} #{plural n "hour" "hours"} ago
DaysAgo n@Int:      #{plural n "yesterday" (number n <> " days ago")}
WeeksAgo n@Int:     #{plural n "last week" (number n <> " weeks ago")}
MonthsAgo n@Int:    #{plural n "last month" (number n <> " months ago")}
YearsAgo n@Int:     #{plural n "last year" (number n <> " years ago")}
