Default: &defaults
  database: coast.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: coast_test.sqlite3
  <<: *defaults

Staging:
  database: coast_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: coast_production.sqlite3
  poolsize: 100
  <<: *defaults
